name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Publish jar
        id: build
        uses: peramic/actions/build-stretch@v1
        with:
          arch: all
          script: ./mkapp
          token: ${{ secrets.ACTIONS }}
